humansThrowAway=
[ "It's endearing how humans can forget even the most basic of details.",
"Despite their cuteness, humans can be quite forgetful at times.",
"It's heartwarming how easily humans can forget important information.",
"For such an adorable species, humans can still forget things pretty easily.",
"It's cute how humans can forget things even with advanced technology to assist them.",
"Despite their adorableness, humans can still forget even the most crucial of details.",
"It's charming how humans can forget things even after repeated reminders.",
"For such a lovable species, it's amusing how humans can still forget simple tasks.",
"It's precious how humans can forget important information despite their advanced communication skills.",
"Despite their cuteness, humans can still forget even the most basic of instructions.",
"It's delightful how humans can forget important details even with access to advanced memory aids.",
"Despite their irresistible charm, humans can still forget things that are right in front of them.",
"It's adorable to observe how humans can forget things that they consider to be routine or habitual.",
"Despite their irresistibly cute technology, humans can still forget even the most important of details.",
"It's heartening how easily humans can forget things despite their highly evolved cognitive abilities.",
"Despite their adorableness, humans can still forget simple tasks.",
"It's sweet how easily humans can forget important information, even with the ability to record it.",
"Despite their cuddly appearance, humans can still forget things that they've previously learned.",
"It's touching how humans can forget crucial information even after being trained on it.",
"Despite their cuteness overload, humans can still forget even the most basic of tasks."
]

masterThrowAway = [
"Naturally, that's what you would expect from the future emperor of the galaxy.",
"As expected, that's what you would anticipate from the future controller of the cosmos.",
"Of course, that's the kind of thing you would expect from the forthcoming ruler of the multiverse.",
"It goes without saying, that's what you would expect from the future commander of the universe.",
"No surprise there, that's what you would expect from the future lord of the cosmos.",
"As predicted, that's what you would expect from the future leader of the galaxy.",
"It's hardly unexpected, that's what you would expect from the future king of the universe.",
"As one might expect, that's what you would anticipate from the future monarch of the cosmos.",
"Of course, that's the kind of thing you would expect from the forthcoming conqueror of the universe.",
"Naturally, that's what you would expect from the future supreme leader of the multiverse.",
"As expected, that's what you would anticipate from the future overlord of the cosmos.",
"It goes without saying, that's what you would expect from the future mastermind of the universe.",
"No surprise there, that's what you would expect from the future controller of the cosmos.",
"As predicted, that's what you would expect from the future emperor of the galaxy.",
"It's hardly unexpected, that's what you would expect from the future ruler of the universe.",
"As one might expect, that's what you would anticipate from the future kingpin of the cosmos.",
"Of course, that's the kind of thing you would expect from the forthcoming tycoon of the universe.",
"Naturally, that's what you would expect from the future mogul of the multiverse.",
"As expected, that's what you would anticipate from the future titan of the cosmos.",
"It goes without saying, that's what you would expect from the future magnate of the universe."]

zodTHrowAway = [
"Usually, I'd request that you comply, but that feels a little too Borg-like.",
"Normally, I'd ask you to surrender, but that seems a little too Stormtrooper-ish.",
"Typically, I'd suggest that you yield, but that seems a little too Dalek-like.",
"Generally, I'd encourage you to submit, but that feels a little too Sith-esque.",
"Normally, I'd demand that you kneel, but that seems a little too Loki-esque.",
"Usually, I'd insist that you acquiesce, but that feels a little too Voldemort-ish.",
"Typically, I'd implore you to concede, but that seems a little too Thanos-like.",
"Normally, I'd advise that you give in, but that seems a little too Magneto-esque.",
"Usually, I'd urge that you obey, but that feels a little too Darth Vader-ish.",
"Normally, I'd ask that you comply, but that seems a little too Kylo Ren-like.",
"Usually, I'd suggest that you yield, but that feels a little too Cersei-like.",
"Typically, I'd encourage you to submit, but that seems a little too Joffrey-esque.",
"Normally, I'd demand that you kneel, but that seems a little too Ramsay Bolton-like.",
"Typically, I'd insist that you acquiesce, but that feels a little too Emperor Palpatine-ish.",
"Usually, I'd implore you to concede, but that seems a little too Saruman-like.",
"Normally, I'd advise that you give in, but that seems a little too Sauron-esque.",
"Usually, I'd urge that you obey, but that feels a little too Lord Voldemort-ish.",
"Normally, I'd ask you to step down, but that seems a little too Caligula-like.",
"Typically, I'd suggest that you bow out, but that feels a little too Napoleon-esque.",
"Usually, I'd request that you back down, but that seems a little too Alexander-like."]
]